import raw from "./catalogue.generated.json";

export type Product = {
  id: string;
  name: string;
  note: string;
  src: string;
  width: number;
  height: number;
  portrait: boolean;
  source: string;
};

export type Category = {
  slug: string;
  title: string;
  tagline: string;
  intro: string;
 
  group: string;
  story: Story | null;
  count: number;
  cover: string | null;
  coverWidth: number;
  coverHeight: number;
  products: Product[];
};

export type Story = { headline: string; materials: string; space: string };

export type Group = { key: string; slug: string; title: string; blurb: string; intro: string };

/** Generated by scripts/build-catalogue.mjs from the folders under image/. */
const data = raw as { groups: Group[]; categories: Category[] };

/** Only categories that actually have pieces — these get routes. */
export function getCategories(): Category[] {
  return data.categories.filter((c) => c.count > 0);
}

/** Including the ones awaiting photography, which still show in the index. */
export function getAllCategories(): Category[] {
  return data.categories;
}

export function getCategory(slug: string): Category | undefined {
  return getCategories().find((c) => c.slug === slug);
}

/** Groups that hold at least one category, each with its categories attached. */
export function getGroups(): (Group & { categories: Category[] })[] {
  return data.groups
    .map((g) => ({ ...g, categories: data.categories.filter((c) => c.group === g.key) }))
    .filter((g) => g.categories.length > 0);
}

/**
 * The chapters of the catalogue: real furniture types, in reading order, each
 * with something to show. "Rooms" is excluded — it is complete interiors rather
 * than a type of thing you can buy — and so is anything not yet photographed.
 */
export function getChapters(): Category[] {
  return data.categories.filter((c) => c.group !== "rooms" && c.count > 0);
}

/** Categories that exist but have nothing to show yet. */
export function getForthcoming(): Category[] {
  return data.categories.filter((c) => c.count === 0);
}

/** Complete interiors, shown as an epilogue rather than a product type. */
export function getRooms(): Category | undefined {
  return data.categories.find((c) => c.group === "rooms" && c.count > 0);
}

export function getProduct(categorySlug: string, productId: string) {
  const category = getCategory(categorySlug);
  const index = category?.products.findIndex((p) => p.id === productId) ?? -1;
  if (!category || index < 0) return undefined;
  return {
    category,
    product: category.products[index],
    previous: category.products[index - 1] ?? null,
    next: category.products[index + 1] ?? null,
    position: index + 1,
  };
}

/** The group a category belongs to — the middle level of the hierarchy. */
export function groupOf(categorySlug: string): Group | undefined {
  const cat = data.categories.find((c) => c.slug === categorySlug);
  return data.groups.find((g) => g.key === cat?.group);
}

/** A group addressed by its own URL segment, with the categories it holds. */
export function getGroupBySlug(slug: string) {
  const group = data.groups.find((g) => g.slug === slug);
  if (!group) return undefined;
  const categories = getCategories().filter((c) => c.group === group.key);
  return categories.length ? { ...group, categories } : undefined;
}

/** Group slugs that have something to show, for static generation. */
export function getGroupSlugs(): string[] {
  return data.groups
    .filter((g) => getCategories().some((c) => c.group === g.key))
    .map((g) => g.slug);
}

export default data.categories;
